language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs-v1
  - iojs-v2
script: npm test
before_script:
  - npm install
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key:
    - secure: Ri/FgMo8X/enXvKcGuch4EvB9AyGcea8XGiyCu2A9awplFlB/2/tT03CoCUA0UfRiUAUD7OpxHwzknvcEHWWEGU1Y6O2iugtETFqzUT8F2j5TX0Q0Yrr7CHBrVKxBNIRo/7vohB1PxtfGFoktaButfS2dKjKMQVLPDG3n4lQnw4YYQU6YWDV9IbffgbgJQuKbJerJbvVGlL4R/qm9+kmkWsiaxaECRSlhhg1C7ExW5nl0RcWCxyWfrX4l+uzYSfPG6ortx8X8exU/jjlbSQdBAue1H7+bRoI6HuRprhFrbyoO5HTT5UpXfSFQhq+oxB8o7TZbzv6EGE8YhlNILY9MWdWDr2HxlVVt3Ni7ygeQEnDW9WBj6RawThVMnXhouYh59B9jkqb98bNbaIQ0+uGKx3p0rjTzepGc14Bh225m7opI7flXDFGCcb/zOqsX6UsJLBVzZECJTDYYvYp+AzwW4ZjqgJo2D2J9Pcj/l7l+L6xGiSLwG3VTJOIITmTQNpgbCHW+wfsSoKlHUKnV74dbnCaaSzYZT7wLLuziqWYBaw/5gaxtLL9ylRPSpF9TTrqF/jvbN+YlngLYSi/gCW2nwrgBvUk8MrSWLgybwPkHY824q0w8H2y2ckReE0zHnfiNItN6GB6xIP2R3b9fxMnBlKCjTbXEvl+rjeROV/H8q4=
env:
  global:
    - secure: MTVqTtbba6LXdAdB6xrp2VfQeDez40bFpwPmSdmlMTDlP0nv4FtM8TiWvRNWhwiGJBFBtTIyezzs/Rwje8kY4CopUsIqEnLzRCr3tr2UydnMNUqU8ELwxW+WDw+LJ+oUmXcqiqjQsWkDS8u1S7a+oRcv35NnsR7cPkVhJ8lwugyK0fz2/U0P76vgxNCbJq5pun4UoQ/uT55VzaJ5+ugjyOPmiwF0pXTiGSFtqi6toxl85YA/j8aO4IIGHOdjBceStcUoKILV/icZc4ea/cLUVSuRRsjoruun1qmmNDJBWBdiMfoyKfVjEl0A4zNMgY8XWI2vvkjfuUWfEftcAO/7EdPbIJFWLEoViRe6ZLw/4LBdGSJFXx/11K/o4f9XRus9OnKrPoSLHvX2Kb0rjIH5J1KlG/KsL0FEV2I1RUhTDm3RLmiQU7/kohe2KXZKd7yZGbgT6qVKNR3+zmA+tthZwk6kjlXFKbrTGry8DAwLWz5piVW3ZOev4bVfYxUS6trMuCplmkPUJ3H1xwDnoU0j56G9yurqbKEnTY90x84KZ67uRwRszPz/XnHq2kiJzQUgPM/TPsoXw/vGQMhifncGZ+iW24UehmY97JjUwJo3jGVKR6auDTNbRNpNortAKV9okC6xrWtPbtICPFe8PRY14prdwG/GOlU/zicz3J22VbM=
    - secure: nfqljCdoIS8KjZUxtsd5v1F1eqDmHwR29MTafGKYRKqiTVNGUMiEqY79VA4Hcmra/JSz0lDrX1ji2IQfrUgRFLzNEXjlA6JBz2R3xEMapkfpVSB7SBpKA49UljcBy5rw/SCmERQJba/BwBeXMOnZYJjL9wDypVfXITx5m+M47kNxEYgjj3TULGAGw2K31ZSDEBxpQXQ0BA1qNCjnJ971CICerlsc6LFpQJgZq17lSAZvJR1RYdLVn5sK1Z2iiir0WYQJv93L8djAYtiMKyWCZ9StYnc0+eUT0//6PBKlPF5jqdNSvqnrtkZbh+BGOf2OBcUEJGwX1R6xerx5rha1sClNh7KpNn8WtB2tzHhFjGtfwMNSfKdtWh+HrP/nKD+agALZVyCpVrxZkg1HoakFqhOxnddhSy/fvvCcV4fAk5yIQTmqEDF+/4IkVFN7NsA8gfbT6wzU9au75B9G5EKAtsZruloYXlIaIDLOSIStqJEqlU3iHwbHFG6kgevpR7Oap5wx68E6C9R+Zai1KxLvRMkxyQNNdK5QtpxHHEZq11lDHvM+RYQIaOjeuzaoDQWxuLA6pPufe27Qvb+RMp8BJhbiJUhhH7/HYwougqgoDJzRDIdNoU+lDKzbK8j4Jai9AU0SBOZx6WOVV84MJ326g0AL6UShfm4aL9yAQGzc5Wo=
