language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs-v1
  - iojs-v2
script: npm test
before_script:
  - npm install
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: famfam-operations@freeallmedia.com
  api_key:
    - secure: pmIYTw4XrvNq7fVL82ixcz710PR8Zhb3fvh4GjkVZjRFBC4bLFjxEYRw70e2bkzSQ2cfqcKt8H4Y4utBVZlNrQatclm0W0Hp9nOlt+izMOmJWQ5lfDuCXZDdewDJImWlB2+v3NYvFtM8zn9cqtY+4tkPfKxLmmcZpT6JtZHtT6VZWHBcxdNptmElkwS+NU0iiueM+/ZeQYWHlOIhoFfN0HhWBHrq6PFzmbG88lfxcWS4OFEgB2SwMI0Q7TCM9G9VHudoHPh7SkldM/NjEJ+igykRPX6ZjYAe3Ireiu2bG0WzM+yrAqVlAM9BDAoLlhf2MXMP8a5RH7gw/MzP/YwmrgwmMY94Dl5/CrHcvea5iqUBiV5qk3wefyHjz2E1akJ7E5tqGWuXru5yuElHi4WQOWTTCPodSnVAbx2P6AvF2U1VzcCKeNJF6S/zaoCdG96AwwGOLuiBNxMPeONAeQ/wUvXL7n8xNXl0xQrQ9hxPawHj2magfeN7tXwP5f+CdZPAHAwJPRfK3Ag2M4+Z9HJdErkNcQYU+hmPBmqSATiSfTrH6mQt9bScwXG30MaoF39DevZnYAyYYQZqd5Yj71Ur/DGnjrDxH12BWoyusWwqVE0+D7tdMpDPYLMfQWRvAndViREamVz91wkIegxySEbahhC8lWhjFJen7AZTznqMSrU=
env:
  global:
    - secure: EfHSxRQkRmRj15QuC7xp+fIT2aTNO84neP/kPj9vGbLQMk7KUyUvJKLvryfYP1sHM/htgqSOIXXDldRV0ZBg1xkIU+VcYHd9vraLvF7Q77xfff+ghAvAqjCNUsIawy8enYtlnCORlr1vPXDFI/hUh4iM9MsOYxG14SVnwoPpTaKbrJWunlgtunBC8ZdBcts+8yx0Scsw05Ii8edYU6rOrpobVDwELPTzmBC45gogDG7rdCiMc5Kn9ZKjkk/Al9dOJFQlm60c7P6yQuf8bhlZc8btiYN+il9pov6B2RYZ2pP7dFt7efZlSTWfmNMvp+c89pGuPggA2xwK51km3YyBAWM4pK2Z6N18OZ4p/HYA0Fa2/Cu9VcMRtXRAs/f6iN8dxD6JpRNn0YfUjv0v3e3wEaWSWyC3MEvVmfzZrdzgVejYHDa0sPIqt+TNMZSlzHSylpaVm3A+VS5cT/ISPdVZD38ZvFgwZFQngeBFT51/4AN8wpGbBXeokyc0pKzar1YRp0smAgkQgag4yC3e++CZCoavsxxE915tBKjA2OHpLQlBmxwXOsg3zrDl4Z/AwfP3ef8WDF5FfEzFXEB4ffEX0wgwkuoATy9S/muYNrN3GMTyyKTnFtgenUBjHwmMvnPtIXz0PuN2pAQWwinK6UdIVjSYJAvJAsqT0dUkOIpEvs8=
    - secure: 3OnpGMAU2CnWsPxg1Ec3l1WlgLhoApRf22qnM6Azd6ZPvJDGF7OcFrEIGEFtVwLOLDTDTk0Xh1S4D4hCTmYbf3h6bVHvNsngnue+SMBMGfJZ1ybNU5Ypdm4ocBNHN+bG+IQFLabEjvHsYSZJn8iSFn7dsM3u1uxxjCFB+3D8eNQ67pzrZryP/HbOXkGOt3sOi5JHjPQOtzFW6ZvawvaX84V7A0pLQiIwGFltN7eGtMULOnP2Lfki/SbZxvBTeA6wJhM/Jx0VPH9y6jP7HV61rL16FJyZBlC/QGU5o3Ih2AmNwf5oxd/zgot24jQBsEX1s+WbJzbqFuFu/QFh8Y2M8Za4aIQXLQEN9AJpAuDHkwL74+SP/rAQrEB2D/SJJ8gs4dBhu9YXD2OA1OjUqcjsfOwKL1TNpnUWJP8Drw0xe7FhxgrX5LntxNDS3krn4D6hYa7Fq4cZxvk2msemYtqvHNLQNHGcTIbqOtFTvHKlDXlvqzDKlD6gCYEniTtBClOaVl6w71DGN5yFBUFzC0e18BSEp6GaJZy4J4qK7YGEmG/aiDFAMRcI6fMXOof3T0HxxZb8OYipG1AS7lNNI9Ra7xDm4l6Zpub+MF7KkD2my/80W73jbk9xw6vzh+zGX/gD+TMMCqKwuRZfyPGTQ0Zfol8Y1p0JGZyno6AHr2xgWbc=
